//! Build script that generates model registry code from models.json.
//!
//! This script runs at compile time and generates type-safe Rust code
//! containing all model metadata from the JSON registry.

use std::env;
use std::fs;
use std::path::Path;

#[path = "build_support/accessors.rs"]
mod accessors;
#[path = "build_support/model_constant.rs"]
mod model_constant;
#[path = "build_support/schema.rs"]
mod schema;
#[path = "build_support/validation.rs"]
mod validation;

use accessors::generate_accessor_functions;
use model_constant::{generate_model_constant, to_pascal_case, to_screaming_snake_case};
use schema::ModelRegistry;
use validation::validate_registry;

fn main() {
    println!("cargo:rerun-if-changed=models.json");
    println!("cargo:rerun-if-changed=build_support/accessors.rs");
    println!("cargo:rerun-if-changed=build_support/model_constant.rs");
    println!("cargo:rerun-if-changed=build_support/schema.rs");
    println!("cargo:rerun-if-changed=build_support/validation.rs");

    let models_json = fs::read_to_string("models.json")
        .expect("Failed to read models.json - ensure it exists in the project root");

    let registry: ModelRegistry = serde_json::from_str(&models_json)
        .expect("Failed to parse models.json - check JSON syntax");

    let total_models = registry.models().count();

    validate_registry(&registry);

    let generated_code = generate_code(&registry);

    // Build scripts must never mutate packaged or checked-in source files.
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("model_registry.rs");
    fs::write(&dest_path, &generated_code).expect("Failed to write generated model registry code");

    println!(
        "cargo:warning=Generated model registry with {} models across {} categories",
        total_models,
        registry.model_categories.len()
    );
}

fn generate_code(registry: &ModelRegistry) -> String {
    let mut code = String::from(
        r"// This file is AUTO-GENERATED by build.rs from models.json
// DO NOT EDIT MANUALLY - changes will be overwritten
// To modify models, edit models.json and rebuild

",
    );

    // Generate EmbeddingDimension enum
    code.push_str(&generate_embedding_dimension_enum());
    code.push_str("\n\n");

    // Generate PoolingStrategy enum and PoolingConfig struct
    code.push_str(&generate_pooling_types());
    code.push_str("\n\n");

    // Generate ModelType enum
    code.push_str(&generate_model_type_enum(registry));
    code.push_str("\n\n");

    // Generate SupportTier enum
    code.push_str(&generate_support_tier_enum());
    code.push_str("\n\n");

    // Generate ModelInfo struct
    code.push_str(&generate_model_info_struct());
    code.push_str("\n\n");

    // Generate individual model constants
    for model in registry.models() {
        code.push_str(&generate_model_constant(model));
        code.push_str("\n\n");
    }

    // Generate registry array
    code.push_str(&generate_registry_array(registry));
    code.push_str("\n\n");

    // Generate accessor functions
    code.push_str(&generate_accessor_functions());

    code
}

fn generate_pooling_types() -> String {
    r"/// Pooling strategy for dense encodings.
///
/// Determines how token-level embeddings are aggregated into a single vector.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PoolingStrategy {
    /// Use the `[CLS]` token embedding (first token).
    ///
    /// Common in BERT-style models where `[CLS]` is trained to represent
    /// the entire sequence.
    Cls,

    /// Average all token embeddings (weighted by attention mask).
    ///
    /// Produces a centroid representation of all tokens, ignoring padding.
    /// Most common strategy in sentence transformers.
    Mean,

    /// Element-wise maximum across all token embeddings.
    ///
    /// Captures the most salient features from any token position.
    Max,

    /// Use the last valid token's embedding.
    ///
    /// Used by decoder-based embedding models (e.g., Qwen3-Embedding)
    /// where bidirectional attention allows the final token to accumulate
    /// information from the entire sequence.
    LastToken,
}

/// Pooling configuration for dense embedding models.
///
/// Specifies how token-level embeddings should be pooled into a single
/// vector representation, and whether the result should be normalized.
#[derive(Debug, Clone, Copy)]
pub struct PoolingConfig {
    /// The pooling strategy to use
    pub strategy: PoolingStrategy,
    /// Whether to L2-normalize the pooled embedding
    pub normalize: bool,
}"
    .to_string()
}

fn generate_embedding_dimension_enum() -> String {
    r#"/// Embedding dimension specification supporting fixed and Matryoshka dimensions.
#[derive(Debug, Clone, PartialEq)]
pub enum EmbeddingDimension {
    /// Fixed dimension size
    Fixed(usize),
    /// Matryoshka representation with variable dimensions
    Matryoshka {
        /// Default/recommended dimension
        default: usize,
        /// Minimum supported dimension
        min: usize,
        /// Maximum supported dimension
        max: usize,
        /// Explicitly supported dimension values
        supported: &'static [usize],
        /// Truncation strategy (when to apply Matryoshka truncation)
        strategy: Option<&'static str>,
    },
}

impl EmbeddingDimension {
    /// Get the default dimension size
    pub fn default_dim(&self) -> usize {
        match self {
            EmbeddingDimension::Fixed(d) => *d,
            EmbeddingDimension::Matryoshka { default, .. } => *default,
        }
    }

    /// Check if a specific dimension is supported
    pub fn supports_dimension(&self, dim: usize) -> bool {
        match self {
            EmbeddingDimension::Fixed(d) => *d == dim,
            EmbeddingDimension::Matryoshka { supported, .. } => {
                supported.contains(&dim)
            }
        }
    }

    /// Get all supported dimensions
    pub fn supported_dimensions(&self) -> Vec<usize> {
        match self {
            EmbeddingDimension::Fixed(d) => vec![*d],
            EmbeddingDimension::Matryoshka { supported, .. } => {
                supported.to_vec()
            }
        }
    }

    /// Get the Matryoshka truncation strategy, if applicable
    pub fn matryoshka_strategy(&self) -> Option<&'static str> {
        match self {
            EmbeddingDimension::Fixed(_) => None,
            EmbeddingDimension::Matryoshka { strategy, .. } => *strategy,
        }
    }
}

impl std::fmt::Display for EmbeddingDimension {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmbeddingDimension::Fixed(d) => write!(f, "{}", d),
            EmbeddingDimension::Matryoshka { default, min, max, strategy, .. } => {
                let strategy_str = strategy.map(|s| format!(" [{}]", s)).unwrap_or_default();
                write!(f, "{} (Matryoshka: {}-{}{})", default, min, max, strategy_str)
            }
        }
    }
}"#
    .to_string()
}

fn generate_model_type_enum(registry: &ModelRegistry) -> String {
    let mut types = std::collections::HashSet::new();
    for model in registry.models() {
        types.insert(&model.model_type);
    }

    let mut variants = types.into_iter().collect::<Vec<_>>();
    variants.sort();

    let mut code = String::from(
        r"/// Type of embedding model.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ModelType {
",
    );

    for variant in &variants {
        let variant_name = to_pascal_case(variant);
        code.push_str("    /// ");
        code.push_str(&variant_name);
        code.push_str(" model\n");
        code.push_str("    ");
        code.push_str(&variant_name);
        code.push_str(",\n");
    }

    code.push_str("}\n");
    code
}

fn generate_support_tier_enum() -> String {
    r"/// Runtime support level for a catalog entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SupportTier {
    /// The model path has passed the project's support and verification bar.
    Supported,
    /// A runtime path exists, but compatibility and output quality remain provisional.
    Experimental,
    /// Metadata is retained for discovery, but Tessera cannot run the model.
    CatalogOnly,
}

impl SupportTier {
    /// Whether this tier exposes a runtime path.
    pub const fn is_runnable(self) -> bool {
        matches!(self, Self::Supported | Self::Experimental)
    }
}"
    .to_string()
}

fn generate_model_info_struct() -> String {
    r#"/// Comprehensive metadata for a model from the registry.
#[derive(Debug, Clone)]
pub struct ModelInfo {
    /// Unique identifier (kebab-case)
    pub id: &'static str,
    /// Model category
    pub model_type: ModelType,
    /// Runtime support level
    pub support_tier: SupportTier,
    /// Concise explanation of the current support level
    pub support_note: &'static str,
    /// Display name
    pub name: &'static str,
    /// HuggingFace Hub repository ID
    pub huggingface_id: &'static str,
    /// Exact HuggingFace repository commit used for artifact loading
    pub revision: Option<&'static str>,
    /// Tokenizer artifact within the pinned repository
    pub tokenizer_file: &'static str,
    /// Model configuration artifact within the pinned repository
    pub config_file: &'static str,
    /// Safetensors artifact or shard index, when published
    pub safetensors_file: Option<&'static str>,
    /// PyTorch weight artifact within the pinned repository
    pub pytorch_file: &'static str,
    /// Organization that released the model
    pub organization: &'static str,
    /// Release year or date
    pub release_date: &'static str,
    /// Architecture type (bert, distilbert, jina-bert, etc.)
    pub architecture_type: &'static str,
    /// Architecture variant
    pub architecture_variant: &'static str,
    /// Whether model has a projection layer
    pub has_projection: bool,
    /// Projection output dimensions (if applicable)
    pub projection_dims: Option<usize>,
    /// Pooling configuration (for dense models)
    pub pooling: Option<PoolingConfig>,
    /// Number of parameters (as string, e.g., "110M")
    pub parameters: &'static str,
    /// Embedding dimension specification (fixed or Matryoshka)
    pub embedding_dim: EmbeddingDimension,
    /// Hidden layer dimensions
    pub hidden_dim: usize,
    /// Maximum sequence length
    pub context_length: usize,
    /// Maximum position embeddings
    pub max_position_embeddings: usize,
    /// Vocabulary size
    pub vocab_size: usize,
    /// Supported languages
    pub languages: &'static [&'static str],
    /// Supported modalities
    pub modalities: &'static [&'static str],
    /// Whether model supports multi-vector embeddings
    pub multi_vector: bool,
    /// Available quantization methods
    pub quantization: &'static [&'static str],
    /// BEIR average score (if available)
    pub beir_avg: f64,
    /// MS MARCO MRR@10 score (if available)
    pub ms_marco_mrr10: f64,
    /// License
    pub license: &'static str,
    /// Description
    pub description: &'static str,
}

impl ModelInfo {
    /// Whether Tessera currently exposes a runtime path for this model.
    pub const fn is_runnable(&self) -> bool {
        self.support_tier.is_runnable()
    }
}"#
    .to_string()
}

fn generate_registry_array(registry: &ModelRegistry) -> String {
    let mut code = String::from(
        r"/// Complete model catalog, including entries without a runtime adapter.
///
/// Use [`runnable_models`] or [`ModelInfo::is_runnable`] before selecting a
/// model for execution. This is generated at compile time from models.json.
pub const MODEL_REGISTRY: &[ModelInfo] = &[
",
    );

    for model in registry.models() {
        let const_name = to_screaming_snake_case(&model.id);
        code.push_str("    ");
        code.push_str(&const_name);
        code.push_str(",\n");
    }

    code.push_str("];\n");
    code
}
