[build]
rustflags = ["-D", "warnings"]  # Deny warnings in CI

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]  # Optimize for Apple Silicon

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]
