"""Static sample corpus used by the embedding comparison notebook."""

DATASET = {
    "technology": [
        "Machine learning models require large datasets for training",
        "Neural networks consist of layers of interconnected nodes",
        "Cloud computing provides scalable infrastructure on demand",
        "Quantum computers use qubits instead of classical bits",
        "Blockchain technology enables decentralized ledger systems",
        "Edge computing processes data closer to the source",
        "Natural language processing helps computers understand human text",
        "Computer vision algorithms can identify objects in images",
        "Cybersecurity protects systems from digital attacks",
        "5G networks offer faster wireless communication speeds",
        "Artificial intelligence is transforming various industries",
        "Deep learning uses neural networks with many layers",
        "GPU acceleration speeds up parallel computations",
        "Containerization simplifies application deployment",
        "Microservices architecture breaks apps into smaller services",
    ],
    "sports": [
        "Basketball requires dribbling, passing, and shooting skills",
        "Soccer is the world's most popular team sport",
        "Tennis matches are played on grass, clay, or hard courts",
        "Swimming builds cardiovascular endurance and muscle strength",
        "Marathon running tests both physical and mental stamina",
        "Baseball combines pitching, batting, and fielding",
        "Golf requires precision and strategic course management",
        "Rock climbing develops strength, balance, and problem-solving",
        "Cycling can be recreational or competitive racing",
        "Volleyball teams rotate positions after winning serve",
        "Boxing demands quick reflexes and tactical thinking",
        "Gymnastics showcases flexibility, strength, and artistry",
        "Track and field includes sprints, jumps, and throws",
        "Rugby is a physical contact sport with continuous play",
        "Surfing combines balance with wave reading skills",
    ],
    "cooking": [
        "Sautéing vegetables in olive oil brings out their natural sweetness",
        "Baking bread requires proper kneading and proofing time",
        "Caramelizing onions develops deep, complex flavors",
        "Marinating meat tenderizes it and adds flavor",
        "Blanching vegetables preserves their bright color",
        "Deglazing a pan creates a flavorful sauce base",
        "Tempering chocolate ensures a smooth, glossy finish",
        "Braising tough cuts of meat makes them tender",
        "Emulsifying creates stable mixtures like mayonnaise",
        "Reducing sauces concentrates their flavors",
        "Grilling adds smoky char to meats and vegetables",
        "Poaching gently cooks delicate foods in liquid",
        "Roasting caramelizes surfaces at high heat",
        "Steaming preserves nutrients in vegetables",
        "Fermenting transforms ingredients into complex flavors",
    ],
    "science": [
        "Photosynthesis converts sunlight into chemical energy",
        "DNA contains the genetic instructions for living organisms",
        "Gravity is the force that attracts objects with mass",
        "Chemical reactions involve breaking and forming bonds",
        "Evolution explains the diversity of life through natural selection",
        "Atoms consist of protons, neutrons, and electrons",
        "The speed of light in vacuum is constant",
        "Cells are the basic building blocks of life",
        "The water cycle circulates water through evaporation and precipitation",
        "Ecosystems involve complex interactions between organisms",
        "Plate tectonics explains continental drift and earthquakes",
        "Neurons transmit electrical signals in the nervous system",
        "Antibodies help the immune system fight pathogens",
        "Mitochondria are the powerhouses of cells",
        "Black holes have gravity so strong light cannot escape",
    ],
    "arts": [
        "Impressionist paintings capture light and momentary effects",
        "Sculpture can be carved, modeled, or assembled",
        "Jazz improvisation creates spontaneous musical expression",
        "Watercolor painting uses transparent pigments on paper",
        "Classical ballet requires years of rigorous training",
        "Photography freezes moments in time through light",
        "Poetry uses language rhythmically to evoke emotion",
        "Opera combines singing, acting, and orchestral music",
        "Abstract art emphasizes form and color over representation",
        "Renaissance art revived classical themes and techniques",
        "Film editing shapes narrative through shot selection",
        "Contemporary dance breaks traditional movement rules",
        "Ceramic pottery is shaped and fired in kilns",
        "Graphic design communicates through visual composition",
        "Street art transforms urban spaces into galleries",
    ],
    "medicine": [
        "Antibiotics fight bacterial infections but not viruses",
        "Vaccination trains the immune system to recognize diseases",
        "MRI scans use magnetic fields to image soft tissues",
        "Physical therapy helps restore mobility after injuries",
        "Chemotherapy targets rapidly dividing cancer cells",
        "Anesthesia blocks pain signals during surgery",
        "Blood pressure measures force against artery walls",
        "Diabetes involves problems regulating blood sugar levels",
        "X-rays use radiation to image bones and dense tissues",
        "Organ transplants can replace failing kidneys or hearts",
        "Gene therapy aims to treat diseases by modifying DNA",
        "Prosthetics replace missing limbs with artificial devices",
        "Cardiac surgery repairs or replaces heart structures",
        "Dermatology treats skin, hair, and nail conditions",
        "Neurosurgery operates on the brain and nervous system",
    ],
}

COLORS_MAP = {
    "technology": "#1f77b4",
    "sports": "#ff7f0e",
    "cooking": "#2ca02c",
    "science": "#d62728",
    "arts": "#9467bd",
    "medicine": "#8c564b",
}
